### ISSUE TITLE
Component fields order matters.

### ISSUE THREAD

**Issue by BrooklinJazz** [APB9785/ECSx#1]
Hi Andrew! @APB9785

Having a blast trying this out. 

I'm trying to make a little factory simulator, and I noticed that the order of atoms in the `fields` param for `Component.add/3` seems to matter.

For example, I have a `Producing` aspect.

```elixir
defmodule Factory.Aspects.Producing do
  @moduledoc """
  Documentation for SampleAspect components.
  """
  use ECSx.Aspect,
    schema: {:entity_id, :type, :per_minute, :to}
end
```

Then when I add a component.

```elixir
    ECSx.Component.add(Producing, [id: id, to: to, type: :iron, per_minute: 30], [
      :type,
      :id,
      :per_minute,
      :to
    ])
```

The order of `fields` changes which values are stored in which field. For example I'm logging all `Producing` components:

```elixir
    ECSx.Component.get_all(Factory.Aspects.Producing, [:id, :type, :per_minute, :to])
    |> IO.inspect()
```

Which prints the following. Notice my fields and values are incorrect.

```elixir
[%{id: :iron, per_minute: 30, to: 4, type: 1}]
```

Perhaps I'm doing something wrong, or maybe this is a bug? Either way, I wanted to get your input on the `fields` params. I wonder if it would be cleaner to exclude `fields` from the function signature entirely?

i.e.

```elixir
ECSx.Component.add(:aspect, [key: "value"])
```

Or am I misunderstanding, and there's a reason to include the `fields` param?

Thank you again for making this and letting me try it out!

**Comment by APB9785** [comment]
Documentation updated
